[General]
frontendId=org.albert.frontend.widgetboxmodel
hotkey=Meta+O
showTray=true

[org.albert.extension.applications]
enabled=true

[org.albert.extension.calculator]
enabled=true

[org.albert.extension.chromium]
enabled=false

[org.albert.extension.files]
enabled=false

[org.albert.extension.firefoxbookmarks]
enabled=false
firefoxPath=/run/current-system/sw/bin/firefox
profile=Profile0
profilesIniPath=~/.mozilla/firefox/profiles.ini

[org.albert.extension.hashgenerator]
enabled=false

[org.albert.extension.python]
enabled=false

[org.albert.extension.system]
enabled=true

[org.albert.extension.terminal]
enabled=false

[org.albert.frontend.qmlboxmodel]
alwaysOnTop=true
clearOnHide=false
hideOnClose=false
hideOnFocusLoss=true
showCentered=true
stylePath=/nix/store/gbqr9ga7ibvvfq22z13n5pssh4xqpb5c-albert-0.17.2/share/albert/org.albert.frontend.qmlboxmodel/styles/BoxModel/MainComponent.qml
windowPosition=@Point(352 127)

[org.albert.frontend.widgetboxmodel]
alwaysOnTop=true
clearOnHide=false
displayIcons=true
displayScrollbar=false
displayShadow=true
hideOnClose=false
hideOnFocusLoss=true
itemCount=5
showCentered=true
theme=Arc Dark Blue
