# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd = {
    availableKernelModules = [ "ahci" "xhci_pci" "usb_storage" "sd_mod" "sdhci_acpi" "rtsx_pci_sdmmc" ];
    kernelModules = [ "vfat" "nls_cp437" "nls_iso8859-1" "usbhid" "dm-snapshot" ];
    luks = {
      devices."lvmroot" = {
        device = "/dev/disk/by-uuid/97e01204-9064-4b9a-9eb5-05d4fd5612c2";
        fallbackToPassword = true;
        gpgCard = {
          gracePeriod = 5;
          publicKey = INSTALL_ROOT/etc/nixos/secrets/luks/yubikey-public.asc;
          encryptedPass = INSTALL_ROOT/etc/nixos/secrets/luks/HOST_NAME-passphrase.asc;
        };
        # yubikey = {
        #   slot = 2;
        #   twoFactor = false;
        #   storage = {
        #     device = "/dev/disk/by-label/NIXBOOT";
        #   };
        # };
      };
      gpgSupport = true;
      # yubikeySupport = true;
    };
  };
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];


  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
      options = [ "defaults" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-label/nixhome";
      fsType = "ext4";
      options = [ "defaults" "noatime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-label/nixswap"; }
    ];

  hardware = {
    bluetooth.enable = true;
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
