# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usb_storage" "sd_mod" "sdhci_acpi" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixroot";
      fsType = "btrfs";
      options = [ "subvol=@" "defaults" "noatime" "autodefrag" "compress=zstd" "ssd" "discard=async" ];
    };

  boot.initrd.luks.devices."nixroot".device = "/dev/disk/by-uuid/96799e6f-7178-43d7-9ca2-12d09ad21c3f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-label/nixroot";
      fsType = "btrfs";
      options = [ "subvol=@home" "defaults" "noatime" "autodefrag" "compress=zstd" "ssd" "discard=async" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-label/nixroot";
      fsType = "btrfs";
      options = [ "subvol=@var-cache" "defaults" "noatime" "autodefrag" "compress=zstd" "ssd" "discard=async" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-label/nixroot";
      fsType = "btrfs";
      options = [ "subvol=@var-log" "defaults" "noatime" "autodefrag" "compress=zstd" "ssd" "discard=async" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-label/nixswap"; }
    ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
